/* Content templates. Theme-agnostic events; app.js renders them per theme.
   Add a scenario = push an object here. Nothing else to wire up. */

const THINK_LABELS = [
  'Thinking', 'Cogitating', 'Pondering', 'Deliberating', 'Reasoning',
  'Working', 'Planning', 'Effort: high', 'Tracing', 'Weighing options',
];

// Mid-run interruptions: whatever the user types gets quoted back.
const FOLLOWUPS = [
  msg => [
    { t: 'think', ms: 4200, lines: [`New instruction mid-flight: "${msg}". Folding that into the plan before touching anything else.`] },
    { t: 'text', lines: ['Got it. Finishing the edit I already started, then applying that on top.'] },
  ],
  msg => [
    { t: 'think', ms: 5600, lines: [`"${msg}" — that changes the scope. Re-checking whether the current diff still holds.`, 'Cheaper to adjust now than to unwind two files later.'] },
    { t: 'tool', name: 'Read', arg: 'CHANGES.md', result: 'Read 41 lines' },
    { t: 'text', lines: ['Re-scoped. Same entry point, narrower change.'] },
  ],
  msg => [
    { t: 'text', lines: [`Noted: ${msg}`] },
    { t: 'tool', name: 'TodoWrite', arg: '3 items', result: 'Updated plan (1 in progress, 2 pending)', ms: 2600 },
  ],
  msg => [
    { t: 'think', ms: 7800, lines: [`Reading "${msg}" as a hard constraint, not a suggestion.`, 'That rules out the shortcut I was about to take. Going the boring route instead.'] },
    { t: 'tool', name: 'Grep', arg: '"legacy_fallback"', result: '6 matches in 4 files' },
  ],
  msg => [
    { t: 'text', lines: [`On it — "${msg}".`, 'One clarification I will assume rather than block on: keeping the public signature unchanged.'] },
    { t: 'wait', ms: 6500, label: 'Re-running the affected suite' },
    { t: 'tool', name: 'Bash', arg: 'pnpm vitest run --changed', result: '31 passed (4.2s)' },
  ],
  msg => [
    { t: 'think', ms: 3400, lines: [`Queued: "${msg}". Applying after the current tool call resolves.`] },
    { t: 'text', lines: ['Done with the pending write. Switching to that now.'] },
  ],
];

const SCENARIOS = [
  {
    id: 'jwt',
    title: 'JWT 만료 경계 버그 추적',
    cwd: '~/Documents/GitHub/api-gateway',
    branch: 'fix/jwt-expiry-boundary',
    prompt: 'auth middleware rejects tokens one second early in staging — find the root cause and fix it',
    events: [
      { t: 'think', ms: 9200, lines: [
        'The report says one second early, which smells less like a comparison operator and more like a unit mismatch: `exp` is seconds, `Date.now()` is milliseconds.',
        'Before editing anything I want every place that touches expiry, not just the one the ticket names — a guard in the shared helper beats four guards in four callers.',
      ] },
      { t: 'tool', name: 'Read', arg: 'src/auth/verifyToken.ts', result: 'Read 142 lines' },
      { t: 'tool', name: 'Grep', arg: '"Date.now\\(\\)" src/auth', result: '7 matches in 4 files' },
      { t: 'text', lines: [
        'Found it. `verifyToken` divides by 1000 before comparing, but `refreshGuard` compares raw milliseconds against `exp`, so any token is "expired" the moment it is issued — except the clock skew allowance masks it down to a one-second window.',
      ] },
      { t: 'tool', name: 'Read', arg: 'src/auth/refreshGuard.ts', result: 'Read 88 lines' },
      { t: 'think', ms: 12500, lines: [
        'Two options: patch `refreshGuard`, or move the comparison into one `isExpired(exp, skewSec)` helper both call.',
        'The second is a slightly bigger diff but kills the whole class of bug. Sibling callers stay broken otherwise.',
      ] },
      { t: 'diff', file: 'src/auth/expiry.ts', add: 12, del: 0, start: 1, hunk: [
        ['+', '/** Single source of truth for token expiry. `exp` is seconds since epoch. */'],
        ['+', 'export function isExpired(exp: number, skewSec = 30, now = Date.now()): boolean {'],
        ['+', '  if (!Number.isFinite(exp)) return true;'],
        ['+', '  const nowSec = Math.floor(now / 1000);'],
        ['+', '  return exp + skewSec <= nowSec;'],
        ['+', '}'],
        ['+', ''],
        ['+', 'export function secondsUntilExpiry(exp: number, now = Date.now()): number {'],
        ['+', '  return exp - Math.floor(now / 1000);'],
        ['+', '}'],
      ] },
      { t: 'diff', file: 'src/auth/refreshGuard.ts', add: 4, del: 6, start: 34, hunk: [
        [' ', 'export async function refreshGuard(req: Request): Promise<Session> {'],
        [' ', '  const claims = decode(req.cookies.session);'],
        ['-', '  const now = Date.now();'],
        ['-', '  if (claims.exp < now) {'],
        ['-', '    throw new UnauthorizedError("session expired");'],
        ['-', '  }'],
        ['-', '  if (claims.exp - now < REFRESH_WINDOW) {'],
        ['+', '  if (isExpired(claims.exp)) {'],
        ['+', '    throw new UnauthorizedError("session expired");'],
        ['+', '  }'],
        ['+', '  if (secondsUntilExpiry(claims.exp) < REFRESH_WINDOW_SEC) {'],
        [' ', '    return rotate(claims);'],
        [' ', '  }'],
      ] },
      { t: 'tool', name: 'Edit', arg: 'src/auth/verifyToken.ts', result: 'Updated verifyToken.ts with 3 additions and 9 removals' },
      { t: 'wait', ms: 14000, label: 'Running the auth suite', tick: f => `${Math.min(38, Math.ceil(f * 38))}/38 tests` },
      { t: 'tool', name: 'Bash', arg: 'pnpm vitest run src/auth', out: [
        '✓ src/auth/expiry.test.ts (11)',
        '✓ src/auth/verifyToken.test.ts (18)',
        '✗ src/auth/refreshGuard.test.ts (9) — 1 failed',
        '  → expected 401, received 200: "rotates a token expiring in 20s"',
      ], fail: true },
      { t: 'think', ms: 8800, lines: [
        'That failure is the test encoding the old bug: `REFRESH_WINDOW` was milliseconds, so 20s never entered the window. The fixture is wrong, not the code.',
      ] },
      { t: 'diff', file: 'src/auth/refreshGuard.test.ts', add: 3, del: 3, start: 61, hunk: [
        ['-', '  const REFRESH_WINDOW = 5 * 60 * 1000;'],
        ['+', '  const REFRESH_WINDOW_SEC = 5 * 60;'],
        [' ', ''],
        ['-', '  it("rotates a token expiring in 20s", async () => {'],
        ['-', '    const exp = Date.now() + 20_000;'],
        ['+', '  it("rotates a token expiring in 20s", async () => {'],
        ['+', '    const exp = Math.floor(Date.now() / 1000) + 20;'],
      ] },
      { t: 'tool', name: 'Bash', arg: 'pnpm vitest run src/auth', result: '38 passed (3.1s)', ms: 7000 },
      { t: 'text', lines: [
        'Root cause: `exp` (seconds) compared against `Date.now()` (milliseconds) in `refreshGuard`, with a 30s skew allowance hiding it down to a one-second window.',
        'Fix: one `isExpired` helper in `src/auth/expiry.ts`, both call sites routed through it, `REFRESH_WINDOW` renamed to `_SEC` so the unit is in the name. Full auth suite green.',
      ] },
    ],
  },

  {
    id: 'pagination',
    title: '커서 페이지네이션 추가 (NestJS)',
    cwd: '~/Documents/GitHub/orders-service',
    branch: 'feat/cursor-pagination',
    prompt: 'the /orders endpoint times out past page 400. move it to cursor pagination without breaking the current clients',
    events: [
      { t: 'think', ms: 11000, lines: [
        'Offset pagination at page 400 means the database is discarding 8000 rows per request. Cursor pagination fixes it, but two mobile builds still send `?page=`.',
        'So: accept both, prefer the cursor, and keep `page` working until the clients age out.',
      ] },
      { t: 'tool', name: 'Read', arg: 'src/orders/orders.controller.ts', result: 'Read 96 lines' },
      { t: 'tool', name: 'Read', arg: 'src/orders/orders.repository.ts', result: 'Read 213 lines' },
      { t: 'tool', name: 'Bash', arg: 'psql -c "\\d+ orders"', out: [
        'Indexes:',
        '  "orders_pkey" PRIMARY KEY, btree (id)',
        '  "orders_customer_id_idx" btree (customer_id)',
      ] },
      { t: 'think', ms: 13500, lines: [
        'There is no index on `(created_at, id)`, which is exactly the tuple a stable cursor needs. Adding the index is the actual performance fix; the API shape is secondary.',
        'Cursor payload: base64 of `created_at|id`. Opaque to clients so I can change it later without a version bump.',
      ] },
      { t: 'diff', file: 'src/orders/dto/list-orders.dto.ts', add: 9, del: 1, start: 12, hunk: [
        [' ', 'export class ListOrdersDto {'],
        ['-', '  @IsInt() @Min(1) page = 1;'],
        ['+', '  /** @deprecated offset paging, kept for app builds < 4.12 */'],
        ['+', '  @IsOptional() @IsInt() @Min(1) page?: number;'],
        ['+', ''],
        ['+', '  @IsOptional() @IsBase64() cursor?: string;'],
        ['+', ''],
        ['+', '  @IsInt() @Min(1) @Max(100) limit = 25;'],
        ['+', ''],
        ['+', '  @IsOptional() @IsIn(["asc", "desc"]) order: "asc" | "desc" = "desc";'],
        [' ', '}'],
      ] },
      { t: 'diff', file: 'src/orders/orders.repository.ts', add: 18, del: 7, start: 74, hunk: [
        ['-', '  async list(customerId: string, page: number, limit: number) {'],
        ['-', '    return this.db.order.findMany({'],
        ['-', '      where: { customerId },'],
        ['-', '      skip: (page - 1) * limit,'],
        ['-', '      take: limit,'],
        ['-', '      orderBy: { createdAt: "desc" },'],
        ['-', '    });'],
        ['+', '  async list(customerId: string, opts: ListOpts) {'],
        ['+', '    const { cursor, limit, order } = opts;'],
        ['+', '    const decoded = cursor ? decodeCursor(cursor) : null;'],
        ['+', ''],
        ['+', '    // (createdAt, id) keyset — stable across inserts, unlike OFFSET'],
        ['+', '    const rows = await this.db.order.findMany({'],
        ['+', '      where: {'],
        ['+', '        customerId,'],
        ['+', '        ...(decoded && {'],
        ['+', '          OR: ['],
        ['+', '            { createdAt: { lt: decoded.createdAt } },'],
        ['+', '            { createdAt: decoded.createdAt, id: { lt: decoded.id } },'],
        ['+', '          ],'],
        ['+', '        }),'],
        ['+', '      },'],
        ['+', '      take: limit + 1,'],
        ['+', '      orderBy: [{ createdAt: order }, { id: order }],'],
        ['+', '    });'],
      ] },
      { t: 'tool', name: 'Write', arg: 'prisma/migrations/20260730_orders_keyset/migration.sql', result: 'Created migration' },
      { t: 'diff', file: 'prisma/migrations/20260730_orders_keyset/migration.sql', add: 3, del: 0, start: 1, hunk: [
        ['+', '-- concurrently: table is 41M rows, cannot hold a write lock'],
        ['+', 'CREATE INDEX CONCURRENTLY IF NOT EXISTS orders_created_at_id_idx'],
        ['+', '  ON orders (customer_id, created_at DESC, id DESC);'],
      ] },
      { t: 'wait', ms: 21000, label: 'Building the index against the staging replica', tick: f => `${(f * 41).toFixed(1)}M/41M rows` },
      { t: 'tool', name: 'Bash', arg: 'psql -f bench/list_orders.sql', out: [
        'before  offset 8000 : 3184 ms  (Seq Scan + Sort)',
        'after   keyset      :   11 ms  (Index Scan orders_created_at_id_idx)',
      ] },
      { t: 'tool', name: 'Bash', arg: 'pnpm test:e2e orders', result: '54 passed (18.9s)', ms: 9500 },
      { t: 'text', lines: [
        'Endpoint now returns `{ data, nextCursor }`. `?page=` still resolves through a shim that converts offset to a cursor on the first hit, so old builds keep working and log a deprecation counter.',
        'The real win was the composite index: 3184ms → 11ms at page 400.',
      ] },
    ],
  },

  {
    id: 'flaky',
    title: 'Playwright 플레이키 테스트 잡기',
    cwd: '~/Documents/GitHub/web-console',
    branch: 'chore/kill-flaky-e2e',
    prompt: 'billing.spec.ts fails about one run in six on CI but never locally. figure out why and make it deterministic',
    events: [
      { t: 'think', ms: 8600, lines: [
        'One in six, CI only, passes locally: that pattern is almost always a race the slower machine loses — or a shared fixture two workers fight over.',
        'Starting from the CI artifacts rather than guessing.',
      ] },
      { t: 'tool', name: 'Bash', arg: 'gh run list --workflow e2e.yml --limit 40 --json conclusion,databaseId', result: '40 runs · 7 failures' },
      { t: 'tool', name: 'Bash', arg: 'gh run view 918237441 --log-failed | tail -40', out: [
        '  1) billing.spec.ts:82 › invoice total updates after coupon',
        '     Expected: "$81.00"',
        '     Received: "$90.00"',
        '     at expect(page.getByTestId("invoice-total")).toHaveText("$81.00")',
      ], fail: true },
      { t: 'tool', name: 'Read', arg: 'e2e/billing.spec.ts', result: 'Read 148 lines' },
      { t: 'think', ms: 15500, lines: [
        'Line 79 clicks Apply, then asserts the total. There is no wait for the mutation to settle — Playwright auto-waits for the element, but the element already exists with the old value, so the assertion can win the race against the response.',
        '`$90.00` is the pre-coupon total, which confirms it: the test read the DOM before React re-rendered.',
        'The lazy fix is a `waitForResponse`. The correct-and-still-lazy fix is asserting on the settled value with a web-first assertion that retries, plus removing the arbitrary `waitForTimeout` three lines up that is papering over the same thing elsewhere.',
      ] },
      { t: 'diff', file: 'e2e/billing.spec.ts', add: 8, del: 5, start: 74, hunk: [
        [' ', '  await page.getByLabel("Coupon code").fill("SAVE10");'],
        ['-', '  await page.getByRole("button", { name: "Apply" }).click();'],
        ['-', '  await page.waitForTimeout(500);'],
        ['-', '  const total = await page.getByTestId("invoice-total").textContent();'],
        ['-', '  expect(total).toBe("$81.00");'],
        ['-', '  await page.waitForTimeout(200);'],
        ['+', '  const applied = page.waitForResponse(r =>'],
        ['+', '    r.url().includes("/api/invoice/preview") && r.status() === 200);'],
        ['+', '  await page.getByRole("button", { name: "Apply" }).click();'],
        ['+', '  await applied;'],
        ['+', ''],
        ['+', '  // web-first assertion: retries until the re-render lands or times out'],
        ['+', '  await expect(page.getByTestId("invoice-total")).toHaveText("$81.00");'],
        ['+', '  await expect(page.getByTestId("coupon-badge")).toBeVisible();'],
      ] },
      { t: 'tool', name: 'Grep', arg: '"waitForTimeout" e2e/', result: '14 matches in 6 files' },
      { t: 'text', lines: [
        'Fourteen more `waitForTimeout` calls across the suite — every one of them is a flake waiting for a slow CI runner. Not fixing all of them in this pass, but they are the same defect.',
      ] },
      { t: 'wait', ms: 26000, label: 'Repeating the spec 30× to prove it', tick: f => `run ${Math.min(120, Math.ceil(f * 120))}/120` },
      { t: 'tool', name: 'Bash', arg: 'npx playwright test billing.spec.ts --repeat-each=30 --workers=4', out: [
        '  120 passed (2.4m)',
        '  0 flaky',
      ] },
      { t: 'tool', name: 'Bash', arg: 'git commit -m "test: remove race in billing coupon spec"', result: '[chore/kill-flaky-e2e 4a1f9c2] 1 file changed, 8 insertions(+), 5 deletions(-)' },
      { t: 'text', lines: [
        'Cause: the assertion read `invoice-total` before the preview mutation resolved; the 500ms sleep was enough on your laptop and not on a loaded runner.',
        '30 repeats × 4 workers, zero flakes. The other 14 sleeps are logged in the PR body as follow-up.',
      ] },
    ],
  },

  {
    id: 'nplus1',
    title: 'Django N+1 쿼리 제거',
    cwd: '~/Documents/Personal/inventory',
    branch: 'perf/warehouse-serializer',
    prompt: 'the warehouse dashboard makes 900+ queries per page load. fix it',
    events: [
      { t: 'think', ms: 7400, lines: [
        '900 queries for one page is a serializer walking relations row by row. django-debug-toolbar will name the exact line faster than reading code.',
      ] },
      { t: 'tool', name: 'Bash', arg: 'python manage.py shell -c "$(cat scripts/profile_dashboard.py)"', out: [
        'total queries: 947',
        'duplicated  : 912',
        '  SELECT ... FROM warehouse_bin WHERE bin.location_id = %s   ×304',
        '  SELECT ... FROM catalog_sku WHERE sku.id = %s               ×304',
        '  SELECT ... FROM stock_count WHERE count.bin_id = %s         ×304',
      ] },
      { t: 'tool', name: 'Read', arg: 'inventory/serializers.py', result: 'Read 176 lines' },
      { t: 'think', ms: 12000, lines: [
        'Three relations, three N+1s, all from `LocationSerializer.get_bins` reaching through `location.bins.all()` per row.',
        '`select_related` handles the forward FK to sku, `prefetch_related` the reverse ones. The catch: the queryset lives in the viewset, not the serializer, so the fix belongs there — otherwise every other caller of this serializer stays slow.',
      ] },
      { t: 'diff', file: 'inventory/views.py', add: 11, del: 3, start: 48, hunk: [
        [' ', 'class WarehouseDashboardView(generics.ListAPIView):'],
        [' ', '    serializer_class = LocationSerializer'],
        [' ', ''],
        ['-', '    def get_queryset(self):'],
        ['-', '        return Location.objects.filter(warehouse=self.kwargs["wh"])'],
        ['+', '    def get_queryset(self):'],
        ['+', '        return ('],
        ['+', '            Location.objects'],
        ['+', '            .filter(warehouse=self.kwargs["wh"])'],
        ['+', '            .select_related("zone")'],
        ['+', '            .prefetch_related('],
        ['+', '                Prefetch("bins", queryset=Bin.objects.select_related("sku")),'],
        ['+', '                Prefetch("bins__counts",'],
        ['+', '                         queryset=StockCount.objects.filter(voided=False)),'],
        ['+', '            )'],
        ['+', '        )'],
      ] },
      { t: 'diff', file: 'inventory/serializers.py', add: 4, del: 6, start: 91, hunk: [
        [' ', '    def get_bins(self, obj):'],
        ['-', '        bins = Bin.objects.filter(location_id=obj.id)'],
        ['-', '        return ['],
        ['-', '            {"sku": Sku.objects.get(id=b.sku_id).code,'],
        ['-', '             "on_hand": b.counts.latest("taken_at").quantity}'],
        ['-', '            for b in bins'],
        ['-', '        ]'],
        ['+', '        # relations are prefetched by the viewset — never re-query here'],
        ['+', '        return [{"sku": b.sku.code,'],
        ['+', '                 "on_hand": latest_count(b.counts.all())}'],
        ['+', '                for b in obj.bins.all()]'],
      ] },
      { t: 'tool', name: 'Grep', arg: '"LocationSerializer" --type py', result: '4 matches in 3 files' },
      { t: 'text', lines: [
        'Three other callers use the same serializer. Two already prefetch; `ExportJob` does not, so it would have kept the N+1. Adding the same prefetch there.',
      ] },
      { t: 'tool', name: 'Edit', arg: 'inventory/tasks.py', result: 'Updated tasks.py with 6 additions and 1 removal' },
      { t: 'wait', ms: 11000, label: 'Re-profiling' },
      { t: 'tool', name: 'Bash', arg: 'python manage.py shell -c "$(cat scripts/profile_dashboard.py)"', out: [
        'total queries: 11   (was 947)',
        'duplicated  : 0',
        'wall time   : 218 ms  (was 6.4 s)',
      ] },
      { t: 'tool', name: 'Bash', arg: 'pytest inventory -q', result: '86 passed, 2 skipped in 12.44s', ms: 8000 },
      { t: 'text', lines: [
        '947 → 11 queries, 6.4s → 218ms. Added an `assertNumQueries(11)` regression test so the next serializer tweak cannot silently reintroduce it.',
      ] },
    ],
  },

  {
    id: 'ratelimit',
    title: 'Redis 레이트리미터 구현 (Go)',
    cwd: '~/Documents/GitHub/edge-proxy',
    branch: 'feat/sliding-window-limiter',
    prompt: 'add per-api-key rate limiting. 1000 req/min, must survive a proxy restart and not stampede redis',
    events: [
      { t: 'think', ms: 16500, lines: [
        'Fixed windows let a client send 2000 requests across a window boundary. A sliding log is exact but stores one entry per request. A sliding window counter over two buckets is the usual compromise — bounded memory, no boundary burst.',
        '"Survive a restart" rules out in-process state, so the counter lives in Redis. "Do not stampede" means one round trip per request and no read-modify-write race, which means a Lua script, not INCR plus EXPIRE.',
      ] },
      { t: 'tool', name: 'Read', arg: 'internal/middleware/chain.go', result: 'Read 118 lines' },
      { t: 'tool', name: 'Grep', arg: '"redis.NewScript"', result: '2 matches in 2 files' },
      { t: 'text', lines: ['There is already a `redisx.Script` wrapper with EVALSHA caching and a reload-on-NOSCRIPT path. Using it instead of writing a second one.'] },
      { t: 'diff', file: 'internal/limiter/sliding.lua', add: 14, del: 0, start: 1, hunk: [
        ['+', '-- KEYS[1] current bucket, KEYS[2] previous bucket'],
        ['+', '-- ARGV[1] limit, ARGV[2] window sec, ARGV[3] elapsed fraction into window'],
        ['+', 'local cur  = tonumber(redis.call("GET", KEYS[1]) or "0")'],
        ['+', 'local prev = tonumber(redis.call("GET", KEYS[2]) or "0")'],
        ['+', 'local est  = prev * (1 - tonumber(ARGV[3])) + cur'],
        ['+', ''],
        ['+', 'if est + 1 > tonumber(ARGV[1]) then'],
        ['+', '  return {0, math.floor(est)}'],
        ['+', 'end'],
        ['+', ''],
        ['+', 'local n = redis.call("INCR", KEYS[1])'],
        ['+', 'if n == 1 then'],
        ['+', '  redis.call("EXPIRE", KEYS[1], tonumber(ARGV[2]) * 2)'],
        ['+', 'end'],
        ['+', 'return {1, math.floor(est) + 1}'],
      ] },
      { t: 'diff', file: 'internal/limiter/limiter.go', add: 21, del: 0, start: 1, hunk: [
        ['+', 'package limiter'],
        ['+', ''],
        ['+', '// Allow reports whether key may spend one request now. One round trip.'],
        ['+', 'func (l *Limiter) Allow(ctx context.Context, key string) (Decision, error) {'],
        ['+', '\tnow := l.clock.Now()'],
        ['+', '\tw := l.window'],
        ['+', '\tbucket := now.Truncate(w).Unix()'],
        ['+', '\telapsed := float64(now.Sub(now.Truncate(w))) / float64(w)'],
        ['+', ''],
        ['+', '\tres, err := l.script.Run(ctx, l.rdb,'],
        ['+', '\t\t[]string{fmt.Sprintf("rl:%s:%d", key, bucket),'],
        ['+', '\t\t\tfmt.Sprintf("rl:%s:%d", key, bucket-int64(w.Seconds()))},'],
        ['+', '\t\tl.limit, int(w.Seconds()), elapsed).Slice()'],
        ['+', '\tif err != nil {'],
        ['+', '\t\t// fail open: a redis outage must not take the edge down'],
        ['+', '\t\tl.metrics.LimiterErrors.Inc()'],
        ['+', '\t\treturn Decision{Allowed: true, Degraded: true}, nil'],
        ['+', '\t}'],
        ['+', '\treturn Decision{Allowed: res[0].(int64) == 1,'],
        ['+', '\t\tUsed: int(res[1].(int64)), Limit: l.limit}, nil'],
        ['+', '}'],
      ] },
      { t: 'think', ms: 9800, lines: [
        'Fail-open is a real decision, not an oversight: this sits in front of paid traffic, so a Redis blip should degrade limiting rather than return 500s. Logging it as degraded so the dashboard shows the gap.',
      ] },
      { t: 'diff', file: 'internal/middleware/ratelimit.go', add: 13, del: 0, start: 22, hunk: [
        ['+', 'func RateLimit(l *limiter.Limiter) Middleware {'],
        ['+', '\treturn func(next http.Handler) http.Handler {'],
        ['+', '\t\treturn http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {'],
        ['+', '\t\t\td, _ := l.Allow(r.Context(), apiKeyFrom(r))'],
        ['+', '\t\t\tw.Header().Set("RateLimit-Limit", strconv.Itoa(d.Limit))'],
        ['+', '\t\t\tw.Header().Set("RateLimit-Remaining", strconv.Itoa(max(0, d.Limit-d.Used)))'],
        ['+', '\t\t\tif !d.Allowed {'],
        ['+', '\t\t\t\tw.Header().Set("Retry-After", "60")'],
        ['+', '\t\t\t\thttp.Error(w, "rate limit exceeded", http.StatusTooManyRequests)'],
        ['+', '\t\t\t\treturn'],
        ['+', '\t\t\t}'],
        ['+', '\t\t\tnext.ServeHTTP(w, r)'],
        ['+', '\t\t})'],
      ] },
      { t: 'wait', ms: 18000, label: 'go test -race ./internal/limiter/...', tick: f => `${Math.min(14, Math.ceil(f * 14))}/14 packages` },
      { t: 'tool', name: 'Bash', arg: 'go test -race ./internal/limiter/...', out: [
        'ok  \tedge-proxy/internal/limiter\t6.812s',
        '--- PASS: TestNoBoundaryBurst (1.02s)',
        '--- PASS: TestFailsOpenOnRedisDown (0.31s)',
        '--- PASS: TestSurvivesRestart (0.44s)',
      ] },
      { t: 'tool', name: 'Bash', arg: 'hey -n 20000 -c 200 -H "X-Api-Key: bench" http://localhost:8080/v1/ping', out: [
        'Status code distribution:',
        '  [200] 1000 responses',
        '  [429] 19000 responses',
        'Latency p99: 2.1 ms   redis calls/request: 1.00',
      ] },
      { t: 'text', lines: [
        'Sliding-window counter over two Redis buckets, one EVALSHA per request, TTL twice the window so a restart inherits the counters.',
        'Boundary burst test passes: 20k concurrent requests admitted exactly 1000. Fails open on Redis loss and marks the decision degraded.',
      ] },
    ],
  },

  {
    id: 'ci',
    title: 'GitHub Actions 캐시 미스 수리',
    cwd: '~/Documents/GitHub/monorepo',
    branch: 'ci/fix-cache-key',
    prompt: 'CI takes 22 minutes and the pnpm cache never hits. find out why',
    events: [
      { t: 'think', ms: 6800, lines: [
        'A cache that never hits is usually a key that includes something changing every run, or a path that does not exist when the save step runs.',
      ] },
      { t: 'tool', name: 'Read', arg: '.github/workflows/ci.yml', result: 'Read 164 lines' },
      { t: 'tool', name: 'Bash', arg: 'gh run view 918240117 --log | grep -iE "cache (hit|miss|saved)"', out: [
        'Cache not found for input keys: Linux-pnpm-8f21c0a...',
        'Cache saved with key: Linux-pnpm-3ba77e1...',
      ] },
      { t: 'think', ms: 10500, lines: [
        'Restore key and save key differ within the same run, so the hash input changes between the two steps. The key hashes `**/pnpm-lock.yaml` — and the build writes a lockfile into `dist/` for the deployable, which the glob then picks up.',
        'Two fixes: narrow the glob, or exclude dist. Narrowing is the smaller change and also makes the key honest.',
      ] },
      { t: 'diff', file: '.github/workflows/ci.yml', add: 7, del: 4, start: 31, hunk: [
        [' ', '      - uses: actions/cache@v4'],
        [' ', '        with:'],
        ['-', '          path: ~/.pnpm-store'],
        ['-', '          key: ${{ runner.os }}-pnpm-${{ hashFiles(\'**/pnpm-lock.yaml\') }}'],
        ['-', '      - run: pnpm install'],
        ['-', '      - run: pnpm -r build'],
        ['+', '          path: ${{ env.STORE_PATH }}'],
        ['+', '          # root lockfile only: dist/ gets a generated one at build time'],
        ['+', '          key: ${{ runner.os }}-pnpm-${{ hashFiles(\'pnpm-lock.yaml\') }}'],
        ['+', '          restore-keys: ${{ runner.os }}-pnpm-'],
        ['+', '      - run: pnpm install --frozen-lockfile'],
        ['+', '      - run: pnpm -r --filter "...[origin/main]" build'],
        ['+', '      - run: pnpm -r --filter "...[origin/main]" test'],
      ] },
      { t: 'text', lines: [
        'Also switched build and test to `--filter "...[origin/main]"` so a docs-only PR stops rebuilding all 34 packages.',
      ] },
      { t: 'tool', name: 'Bash', arg: 'git push -u origin ci/fix-cache-key', result: 'branch published' },
      { t: 'wait', ms: 32000, label: 'Waiting on the CI run to compare timings', tick: f => ['queued', 'install', 'build', 'test'][Math.min(3, Math.floor(f * 4))] },
      { t: 'tool', name: 'Bash', arg: 'gh run watch 918241903', out: [
        '✓ install (cache hit: Linux-pnpm-3ba77e1)   14s',
        '✓ build  (6 of 34 packages affected)      1m 52s',
        '✓ test   (6 affected)                     2m 31s',
        'Total: 4m 58s  (was 22m 07s)',
      ] },
      { t: 'text', lines: [
        'Cause: `hashFiles(\'**/pnpm-lock.yaml\')` matched a lockfile the build itself generates in `dist/`, so restore and save keys never agreed.',
        '22m → 5m. The affected-package filter is most of the win; the cache fix is the other third.',
      ] },
    ],
  },

  {
    id: 'rerender',
    title: 'React 리렌더 폭주 진단',
    cwd: '~/Documents/GitHub/web-console',
    branch: 'perf/table-rerenders',
    prompt: 'typing in the filter box freezes the table for ~400ms per keystroke. profile it and fix the real cause',
    events: [
      { t: 'think', ms: 8200, lines: [
        'Per-keystroke freeze on a table means every row re-renders on every change. Before reaching for memo everywhere, I want the profiler to say which component and why — memoizing the wrong layer just adds comparison cost.',
      ] },
      { t: 'tool', name: 'Bash', arg: 'node scripts/profile-render.mjs --interaction=filter-type', out: [
        'commit 1: 412 ms  — DataTable (2,104 nodes)',
        '  why-did-you-render: TableRow ×1052 — props.rowStyle changed (deep equal)',
        '  why-did-you-render: TableRow ×1052 — props.onSelect changed (deep equal)',
      ] },
      { t: 'tool', name: 'Read', arg: 'src/components/DataTable.tsx', result: 'Read 284 lines' },
      { t: 'think', ms: 13800, lines: [
        'Both culprits are new references created inside the parent render: an inline `rowStyle={{ ... }}` object and an arrow `onSelect={() => ...}`. Deep-equal but reference-unequal, so `React.memo` on TableRow — which is already there — never short-circuits.',
        'The lazy correct fix is hoisting the style object out of the component (it never changes) and wrapping the callback in `useCallback` with the right deps. No new abstraction, no virtualization needed at 1000 rows.',
      ] },
      { t: 'diff', file: 'src/components/DataTable.tsx', add: 10, del: 6, start: 1, hunk: [
        [' ', 'import { memo, useCallback, useMemo } from "react";'],
        ['+', ''],
        ['+', '// hoisted: constant across every render, so the reference is stable'],
        ['+', 'const ROW_STYLE = { contain: "layout paint", height: 36 } as const;'],
      ] },
      { t: 'diff', file: 'src/components/DataTable.tsx', add: 9, del: 7, start: 132, hunk: [
        [' ', '  const rows = useMemo(() => filterRows(data, query), [data, query]);'],
        ['+', ''],
        ['+', '  const handleSelect = useCallback('],
        ['+', '    (id: string) => dispatch({ type: "select", id }),'],
        ['+', '    [dispatch],'],
        ['+', '  );'],
        [' ', ''],
        [' ', '  return rows.map(row => ('],
        ['-', '    <TableRow'],
        ['-', '      key={row.id}'],
        ['-', '      row={row}'],
        ['-', '      rowStyle={{ contain: "layout paint", height: 36 }}'],
        ['-', '      onSelect={() => dispatch({ type: "select", id: row.id })}'],
        ['-', '    />'],
        ['+', '    <TableRow key={row.id} row={row} rowStyle={ROW_STYLE} onSelect={handleSelect} />'],
        [' ', '  ));'],
      ] },
      { t: 'tool', name: 'Grep', arg: '"style={{" src/components', result: '23 matches in 11 files' },
      { t: 'text', lines: ['23 more inline style objects elsewhere. Only the ones inside list children matter; noting them rather than sweeping the whole directory in a perf PR.'] },
      { t: 'wait', ms: 12000, label: 'Re-profiling the same interaction' },
      { t: 'tool', name: 'Bash', arg: 'node scripts/profile-render.mjs --interaction=filter-type', out: [
        'commit 1: 9 ms  — DataTable (2,104 nodes)',
        '  TableRow re-renders: 0 of 1052',
        'INP p75: 412 ms → 24 ms',
      ] },
      { t: 'tool', name: 'Bash', arg: 'pnpm vitest run src/components', result: '112 passed (6.8s)', ms: 7000 },
      { t: 'text', lines: [
        'Cause was reference churn, not row count: an inline style object and an inline arrow defeated the existing `React.memo` on every keystroke.',
        'INP p75 412ms → 24ms with a 19-line diff. No virtualization, no new deps.',
      ] },
    ],
  },

  {
    id: 'migrate',
    title: '스키마 마이그레이션 + 백필',
    cwd: '~/Documents/GitHub/billing',
    branch: 'feat/split-customer-name',
    prompt: 'split customers.full_name into given_name and family_name. 12M rows, zero downtime, and the app can not stop writing during it',
    events: [
      { t: 'think', ms: 19500, lines: [
        'This is an expand-migrate-contract, not one migration. If I drop `full_name` in the same deploy that adds the new columns, every in-flight writer breaks.',
        'Four steps: add nullable columns, dual-write from the app, backfill in batches, then read from the new columns and drop the old one in a later release. The batching matters — one UPDATE over 12M rows holds locks and blows up replication lag.',
        'Also: name splitting is lossy. "van der Berg", mononyms, and CJK names have no space to split on. The backfill must record what it could not confidently split instead of guessing.',
      ] },
      { t: 'tool', name: 'Bash', arg: 'psql -c "SELECT count(*), count(*) FILTER (WHERE full_name !~ \' \') AS no_space FROM customers"', out: [
        '  count   | no_space',
        ' 12043118 |   418902',
      ] },
      { t: 'text', lines: ['419k rows have no space at all — 3.5%. Those get `family_name = NULL` and a flag, not a guess.'] },
      { t: 'diff', file: 'migrations/0141_add_name_columns.sql', add: 6, del: 0, start: 1, hunk: [
        ['+', '-- expand phase: nullable, no default, no rewrite of the table'],
        ['+', 'ALTER TABLE customers'],
        ['+', '  ADD COLUMN given_name  text,'],
        ['+', '  ADD COLUMN family_name text,'],
        ['+', '  ADD COLUMN name_split_confidence text;  -- exact | heuristic | manual_review'],
        ['+', 'CREATE INDEX CONCURRENTLY customers_family_name_idx ON customers (family_name);'],
      ] },
      { t: 'diff', file: 'app/models/customer.rb', add: 12, del: 2, start: 44, hunk: [
        [' ', '  before_save :sync_name_columns'],
        [' ', ''],
        ['+', '  # dual-write while the backfill runs; removed in the contract release'],
        ['+', '  def sync_name_columns'],
        ['+', '    return unless full_name_changed?'],
        ['+', '    split = NameSplitter.call(full_name)'],
        ['+', '    self.given_name             = split.given'],
        ['+', '    self.family_name            = split.family'],
        ['+', '    self.name_split_confidence  = split.confidence'],
        ['+', '  end'],
        ['+', ''],
        ['-', '  def display_name'],
        ['-', '    full_name'],
        ['+', '  def display_name'],
        ['+', '    [given_name, family_name].compact.join(" ").presence || full_name'],
        [' ', '  end'],
      ] },
      { t: 'tool', name: 'Write', arg: 'lib/tasks/backfill_names.rake', result: 'Created backfill task' },
      { t: 'diff', file: 'lib/tasks/backfill_names.rake', add: 15, del: 0, start: 1, hunk: [
        ['+', '# Batched so replicas keep up. Resumable: driven off the null marker,'],
        ['+', '# so a crash mid-run just continues where it stopped.'],
        ['+', 'task backfill_names: :environment do'],
        ['+', '  loop do'],
        ['+', '    batch = Customer.where(name_split_confidence: nil).limit(2_000)'],
        ['+', '    break if batch.empty?'],
        ['+', ''],
        ['+', '    Customer.transaction { batch.each { |c| c.update_columns(**split_of(c)) } }'],
        ['+', ''],
        ['+', '    lag = ReplicaLag.seconds'],
        ['+', '    if lag > 5'],
        ['+', '      warn "replica lag #{lag}s — pausing"'],
        ['+', '      sleep 30'],
        ['+', '    end'],
        ['+', '    sleep 0.2'],
        ['+', '  end'],
        ['+', 'end'],
      ] },
      { t: 'wait', ms: 34000, label: 'Backfilling 12,043,118 rows (batch 2000, lag-aware)', tick: f => `batch ${Math.min(6022, 1 + Math.floor(f * 6022))}/6022` },
      { t: 'tool', name: 'Bash', arg: 'bundle exec rake backfill_names', out: [
        'batch 1/6022 … batch 6022/6022',
        'exact            : 11,406,884',
        'heuristic        :    217,332',
        'manual_review    :    418,902',
        'max replica lag  : 3.1s   (paused 0 times)',
        'elapsed          : 41m 18s',
      ] },
      { t: 'tool', name: 'Bash', arg: 'psql -f checks/name_parity.sql', out: [
        'rows where display_name != full_name: 0',
        'rows with null confidence           : 0',
      ] },
      { t: 'text', lines: [
        'Expand phase shipped: new columns added nullable, app dual-writes, 12M rows backfilled in 41m with peak replica lag 3.1s.',
        '418,902 mononym rows are flagged `manual_review` rather than split wrongly — they still render correctly because `display_name` falls back to `full_name`.',
        'Dropping `full_name` is a separate PR after two releases of dual-write. I did not do it here on purpose.',
      ] },
    ],
  },

  {
    id: 'oncall',
    title: '새벽 장애 대응 (p99 급등)',
    cwd: '~/Documents/GitHub/checkout',
    branch: 'hotfix/p99-spike',
    prompt: 'p99 on /checkout jumped from 180ms to 4.2s twenty minutes ago. nothing deployed. find it',
    events: [
      { t: 'think', ms: 7200, lines: [
        'No deploy means config, data, or a dependency. Twenty minutes is recent enough that the traces still exist — starting there rather than reading code.',
      ] },
      { t: 'tool', name: 'Bash', arg: 'curl -s "$GRAFANA/api/ds/query" -d @queries/p99_by_span.json | jq -r .rows[]', out: [
        'span                          p99_before  p99_now',
        'checkout.total                    182ms     4210ms',
        'checkout.tax.quote                 22ms     3980ms   ← ',
        'checkout.payment.authorize         96ms      101ms',
        'checkout.db.write                  14ms       15ms',
      ] },
      { t: 'text', lines: ['Tax quote provider. Everything else is flat, so this is their latency leaking into our request path.'] },
      { t: 'tool', name: 'Bash', arg: 'grep -c "tax_quote_timeout" /var/log/checkout/current', result: '0' },
      { t: 'tool', name: 'Read', arg: 'src/tax/client.ts', result: 'Read 74 lines' },
      { t: 'think', ms: 11500, lines: [
        'The client has no timeout at all — it inherits the global 30s agent default. And there is no circuit breaker, so every request waits on a degraded vendor instead of falling back to the cached rate table we already maintain.',
        'The vendor being slow is their problem. Us having no timeout is ours, and that is the part I can fix at 3am.',
      ] },
      { t: 'diff', file: 'src/tax/client.ts', add: 16, del: 3, start: 18, hunk: [
        ['-', 'export async function quote(cart: Cart): Promise<TaxQuote> {'],
        ['-', '  const res = await fetch(`${BASE}/quote`, { method: "POST", body: json(cart) });'],
        ['-', '  return res.json();'],
        ['+', 'const TIMEOUT_MS = 400;  // p99 of a healthy provider is 22ms'],
        ['+', ''],
        ['+', 'export async function quote(cart: Cart): Promise<TaxQuote> {'],
        ['+', '  if (breaker.isOpen()) return cachedRateQuote(cart);'],
        ['+', ''],
        ['+', '  try {'],
        ['+', '    const res = await fetch(`${BASE}/quote`, {'],
        ['+', '      method: "POST",'],
        ['+', '      body: json(cart),'],
        ['+', '      signal: AbortSignal.timeout(TIMEOUT_MS),'],
        ['+', '    });'],
        ['+', '    breaker.success();'],
        ['+', '    return await res.json();'],
        ['+', '  } catch (err) {'],
        ['+', '    breaker.failure(err);'],
        ['+', '    metrics.taxFallback.inc({ reason: reasonOf(err) });'],
        ['+', '    return cachedRateQuote(cart);   // stale-but-correct table, refreshed daily'],
        ['+', '  }'],
        [' ', '}'],
      ] },
      { t: 'tool', name: 'Bash', arg: 'pnpm vitest run src/tax', result: '19 passed (2.2s)' },
      { t: 'tool', name: 'Bash', arg: 'pnpm build && ./scripts/deploy.sh --canary 5', out: [
        'canary 5% → healthy after 90s',
        'p99 (canary): 191 ms',
        'p99 (baseline): 4184 ms',
        'tax_fallback rate: 71%',
      ] },
      { t: 'wait', ms: 24000, label: 'Watching the canary before ramping' },
      { t: 'tool', name: 'Bash', arg: './scripts/deploy.sh --ramp 100', out: [
        'ramp 25% → 50% → 100% ok',
        'p99: 188 ms',
      ] },
      { t: 'text', lines: [
        'Trigger was the tax vendor, but the incident was ours: no timeout on their client, so a slow dependency became our latency.',
        'Shipped a 400ms timeout, a circuit breaker, and a fallback to the cached rate table. p99 back to 188ms with 71% of quotes served from cache while they recover.',
        'Follow-ups for the morning: audit every outbound client for a missing timeout, and alert on `tax_fallback` rate so this is loud next time.',
      ] },
    ],
  },

  {
    id: 'refactor',
    title: '레거시 결제 모듈 정리',
    cwd: '~/Documents/GitHub/payments-core',
    branch: 'refactor/kill-strategy-factory',
    prompt: 'PaymentStrategyFactoryProvider has one implementation and 400 lines. delete the abstraction if nothing needs it',
    events: [
      { t: 'think', ms: 9600, lines: [
        'A factory with one product is usually dead weight, but "usually" is not "always" — DI containers and tests sometimes bind against the interface. Checking every reference before deleting a line.',
      ] },
      { t: 'tool', name: 'Grep', arg: '"PaymentStrategyFactory" -r src test', result: '31 matches in 12 files' },
      { t: 'tool', name: 'Bash', arg: 'rg -l "implements PaymentStrategy\\b" src', out: ['src/strategies/StripeStrategy.ts'] },
      { t: 'text', lines: ['One implementation, as suspected. Of the 31 references, 22 are imports of the type and 6 are in a test that mocks the factory to return the only real implementation.'] },
      { t: 'think', ms: 14200, lines: [
        'The remaining three are interesting: `LegacyAdyenAdapter` registers itself with the factory at module load. It is not in the type search because it uses a string key.',
        'So the abstraction does have two products — one of them just registers dynamically, which is why nobody noticed. Deleting the factory outright would silently drop Adyen.',
        'Revised plan: keep a two-line map instead of the 400-line factory, and keep both strategies. Still a deletion, just not the one the ticket asked for.',
      ] },
      { t: 'tool', name: 'Read', arg: 'src/legacy/LegacyAdyenAdapter.ts', result: 'Read 210 lines' },
      { t: 'tool', name: 'Bash', arg: 'psql -c "SELECT provider, count(*) FROM payments WHERE created_at > now() - interval \'30 days\' GROUP BY 1"', out: [
        ' provider | count  ',
        ' stripe   | 482113',
        ' adyen    |     19',
      ] },
      { t: 'text', lines: ['19 Adyen payments in 30 days, all from two enterprise accounts. Live traffic, so it stays.'] },
      { t: 'diff', file: 'src/strategies/registry.ts', add: 8, del: 0, start: 1, hunk: [
        ['+', 'import { StripeStrategy } from "./StripeStrategy";'],
        ['+', 'import { LegacyAdyenAdapter } from "../legacy/LegacyAdyenAdapter";'],
        ['+', ''],
        ['+', '/** Replaces PaymentStrategyFactoryProvider. Two entries, no indirection. */'],
        ['+', 'export const STRATEGIES = {'],
        ['+', '  stripe: new StripeStrategy(),'],
        ['+', '  adyen: new LegacyAdyenAdapter(),'],
        ['+', '} as const;'],
      ] },
      { t: 'tool', name: 'Bash', arg: 'git rm src/factories/PaymentStrategyFactoryProvider.ts src/factories/AbstractStrategyBuilder.ts src/factories/StrategyRegistrationToken.ts', out: [
        "rm 'src/factories/PaymentStrategyFactoryProvider.ts'",
        "rm 'src/factories/AbstractStrategyBuilder.ts'",
        "rm 'src/factories/StrategyRegistrationToken.ts'",
      ] },
      { t: 'tool', name: 'Bash', arg: 'pnpm tsc --noEmit', result: '0 errors', ms: 11000 },
      { t: 'wait', ms: 16000, label: 'Running the payments suite plus contract tests' },
      { t: 'tool', name: 'Bash', arg: 'pnpm test -- payments', out: [
        '✓ 204 passed',
        '  contract: stripe  ✓ 41',
        '  contract: adyen   ✓ 18',
      ] },
      { t: 'text', lines: [
        '612 lines deleted, 8 added. Both providers still route correctly.',
        'One correction to the premise: there were two implementations, not one — `LegacyAdyenAdapter` registered by string key, which is why the type search missed it and why it still handles 19 live payments a month. Deleting the factory blindly would have broken those.',
      ] },
    ],
  },
];

if (typeof module !== 'undefined' && module.exports) module.exports = { SCENARIOS, FOLLOWUPS, THINK_LABELS };
